= CloudBees action: Scan containers with TruffleHog

Use this action to scan Docker images with TruffleHog, an open-source secret scanning tool to detect secrets and sensitive information.

== Prerequisites

This action requires prior authentication to the container registry, so you must invoke the Docker registry authentication action before invoking the TruffleHog container scan action.
 For more information, refer to link:https://github.com/cloudbees-io/configure-oci-credentials[the OCI credentials configuration action].

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `image-location`
| string
| Yes
| Repository location of the Docker image.

| `image-tag`
| string
| Yes
| Tag of the Docker image.

| `only-verified`
| string
| No
| Enable verified flag to scan only verified secrets (Default set to true).

Note:  If only-verified is set to true, Trufflelog tool may utilize an external third-party api to verify the secrets detected. 
Customers concerned about security implications involving third-party api calls should set the only-verified value to false which returns all the secrets without verification and might contain false positives. 

Refer the documentation regarding the credential verification link:https://github.com/trufflesecurity/trufflehog?tab=readme-ov-file#what-is-credential-verification[here]

| `threshold-very-high`
| integer
| No
| The number threshold of very high severity vulnerabilities at which the build is broken.

|=== 

== Usage examples

In your YAML file, add:

[source,yaml]
----

      - name: Check out repo
        uses: actions/checkout@v1

      - name: Sign in to OCI registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: ${{ vars.OCI_REGISTRY }}
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}

      - name: Run TruffleHog container scan
        uses: cloudbees-io/trufflehog-secret-scan-container@v1
        with:
          image-location: ${{ vars.IMAGE_LOCATION }}
          image-tag: ${{ vars.IMAGE_TAG }}
----

In the following example, if there are more than three very high severity vulnerabilities identified, the build is broken.

[source,yaml]
----

      - name: Run TruffleHog container scan with threshold
        uses: cloudbees-io/trufflehog-secret-scan-container@v1
        with:
          image-location: ${{ vars.IMAGE_LOCATION }}
          image-tag: ${{ vars.IMAGE_TAG }}
          threshold-very-high: 3
----

In the following example, setting only-verified to false

[source,yaml]
----

      - name: Run TruffleHog container scan with threshold
        uses: cloudbees-io/trufflehog-secret-scan-container@v1
        with:
          image-location: ${{ vars.IMAGE_LOCATION }}
          image-tag: ${{ vars.IMAGE_TAG }}
          threshold-very-high: 3
          only-verified: false
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
