= CloudBees action: Scan containers with TruffleHog

Use this action to scan Docker images with TruffleHog, an open-source secret scanning tool to detect secrets and sensitive information.

== Prerequisites

This action requires prior authentication to the container registry, so you must invoke the Docker registry authentication action before invoking the TruffleHog container scan action.
 For more information, refer to link:https://github.com/cloudbees-io/configure-oci-credentials[The OCI credentials configuration action].

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required
| Description

| `image-location`
| string
| Yes
| Repository location of the Docker image.

| `image-tag`
| string
| Yes
| Tag of the Docker image.

| `threshold-very-high`
| string
| No
| The number threshold of very high severity vulnerabilities at which the build is broken.

|=== 

== Usage examples

In your YAML file, add:

[source,yaml]
----
      - name: Run TruffleHog container scan
        uses: cloudbees-io/trufflehog-secret-scan-container@v1
        with:
          image-location: ${{ vars.IMAGE_LOCATION }}
          image-tag: ${{ vars.IMAGE_TAG }}
----

In the following example, if there are more than three vulnerabilities of very high severity (`threshold-very-high: 3`) identified, the build is broken.

[source,yaml]
----

      - name: Run TruffleHog container scan with threshold
        uses: cloudbees-io/trufflehog-secret-scan-container@v1
        with:
          image-location: ${{ vars.IMAGE_LOCATION }}
          image-tag: ${{ vars.IMAGE_TAG }}
          threshold-very-high: 3
----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/actions[using actions in CloudBees workflows].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
